apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: u-afmk44mea2
    field.cattle.io/publicEndpoints: '[{"nodeName":"local:machine-7wxpl","addresses":["10.1.1.116"],"port":25,"protocol":"TCP","podName":"smtp:relay-68c599f8b8-kq86q","allNodes":false}]'
  creationTimestamp: "2021-11-23T01:43:31Z"
  generation: 5
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-smtp-relay
  name: relay
  namespace: smtp
  resourceVersion: "110744"
  selfLink: /apis/apps/v1/namespaces/smtp/deployments/relay
  uid: 07a7efc7-e29a-4d9d-909a-ff2b82a5bf85
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-smtp-relay
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-18T22:00:39Z"
        field.cattle.io/ports: '[[{"containerPort":25,"dnsName":"relay-hostport","hostPort":25,"kind":"HostPort","name":"tcp25","protocol":"TCP","sourcePort":25}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-smtp-relay
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: exim4
            optional: false
        - secretRef:
            name: aws-ses
            optional: false
        image: ghcr.io/buildinglink/email/smtp:latest
        imagePullPolicy: Always
        name: relay
        ports:
        - containerPort: 25
          hostPort: 25
          name: tcp25
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
      - name: git-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-23T01:43:31Z"
    lastUpdateTime: "2021-11-23T01:43:34Z"
    message: ReplicaSet "relay-68c599f8b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-23T06:36:17Z"
    lastUpdateTime: "2021-11-23T06:36:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
